---
- name: Include Snapd deployment role
  ansible.builtin.include_role:
    name: acropia.deploy.snapd_deploy

- name: Install Certbot using snap
  community.general.snap:
    name: certbot
    classic: true

- name: Create symlink for certbot to its snap
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    owner: root
    group: root
    state: link
