---
- name: Configure basic audit settings
  ansible.builtin.copy:
    src: /usr/share/audit/sample-rules/10-base-config.rules
    dest: /etc/audit/rules.d/10-base-config.rules
    remote_src: yes

- name: Configure STIG ruleset
  ansible.builtin.copy:
    src: /usr/share/audit/sample-rules//30-stig.rules
    dest: /etc/audit/rules.d/30-stig.rules
    remote_src: yes

- name: Configure final ruleset
  ansible.builtin.copy:
    src: /usr/share/audit/sample-rules/99-finalize.rules
    dest: /etc/audit/rules.d/99-finalize.rules
    remote_src: yes

- name: Regenerate audit rules
  ansible.builtin.command: augenrules --load
