---
- name: Install Zabbix GPG key
  ansible.builtin.rpm_key:
    key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
    state: present

- name: Install Zabbix GPG key
  ansible.builtin.rpm_key:
    key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-08EFA7DD
    state: present

- name: Install Zabbix GPG key
  ansible.builtin.rpm_key:
    key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-79EA5ED4
    state: present

- name: Install Zabbix yum repository
  ansible.builtin.dnf:
    name: https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-1.el9.noarch.rpm
    state: present

- name: Patch EPEL repo file to exclude Zabbix packages
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/epel.repo
    firstmatch: true
    insertafter: "^\\[epel\\]"
    line: "excludepkgs=zabbix*"
