---
- name: Install arpwatch
  ansible.builtin.package:
    name: arpwatch
    state: present

- name: Enable and start arpwatch service
  ansible.builtin.systemd:
    name: arpwatch
    enabled: true
    state: started
