---
- name: Add modprobe blocklist
  ansible.builtin.copy:
    src: modprobe/blocklist.conf
    dest: /etc/modprobe.d/blocklist.conf
    owner: root
    group: root
    mode: 0644

- name: Disable freevxfs filesystem using modprobe
  ansible.builtin.copy:
    src: modprobe/freevxfs.conf
    dest: /etc/modprobe.d/freevxfs.conf
    owner: root
    group: root
    mode: 0644
