---
- name: Set default SSH Daemon config
  ansible.builtin.copy:
    src: ssh/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
  notify:
    - restart sshd
