---
# CIS Controls Linux Benchmark
# Benchmark: Ensure core dumps are restricted
# Description:
#   A core dump is the memory of an executable program. It is generally used to
#   determine why a program aborted. It can also be used to glean confidential
#   information from a core file. The system provides the ability to set a soft
#   limit for core dumps, but this can be overridden by the user.
- name: Restrict core dumps (fs.suid_dumpable)
  ansible.posix.sysctl:
    name: fs.suid_dumpable
    value: '0'
    sysctl_set: true

- name: Restrict unprivileged users from using dmesg (dmesg_restrict)
  ansible.posix.sysctl:
    name: kernel.dmesg_restrict
    value: '1'
    sysctl_set: true

- name: Restrict exposing kernel addresses (kptr_restrict)
  ansible.posix.sysctl:
    name: kernel.kptr_restrict
    value: '2'
    sysctl_set: true

- name: Disable Linux Magic System Request (sysrq)
  ansible.posix.sysctl:
    name: kernel.sysrq
    value: '0'
    sysctl_set: true

# CIS Controls Linux Benchmark
# Benchmark: Ensure ICMP redirects are not accepted
# Description:
#   ICMP redirect messages are packets that convey routing information and tell
#   your host (acting as a router) to send packets via an alternate path. It is
#   a way of allowing an outside routing device to update your system routing
#   tables. By setting accept_redirects 0, the system will not accept any ICMP
#   redirect messages, and therefore, won't allow outsiders to update the
#   system's routing tables.
- name: Disabe IPv4 redirection acceptance (all.accept_redirects)
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: '0'
    sysctl_set: true

- name: Disabe IPv4 redirection acceptance (default.accept_redirects)
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.accept_redirects
    value: '0'
    sysctl_set: tru

- name: Disabe IPv6 redirection acceptance (all.accept_redirects)
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.accept_redirects
    value: '0'
    sysctl_set: true

- name: Disabe IPv6 redirection acceptance (default.accept_redirects)
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.accept_redirects
    value: '0'
    sysctl_set: true


# CIS Controls Linux Benchmark
# Benchmark: Ensure source routed packets are not accepted
# Description:
#   In networking, source routing allows a sender to partially or fully specify
#   the route packets take through a network. In contrast, non-source routed
#   packets travel a path determined by routers in the network. In some cases,
#   systems may not be routable or reachable from some locations (e.g. private
#   addresses vs. Internet routable), and so source routed packets would need to
#   be used.
- name: Disabe IPv4 SRR acceptance (all.accept_source_route)
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.accept_source_route
    value: '0'
    sysctl_set: true

- name: Disabe IPv4 SRR acceptance (default.accept_source_route)
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.accept_source_route
    value: '0'
    sysctl_set: true


# CIS Controls Linux Benchmark
# Benchmark: Ensure packet redirect sending is disabled
# Description:
#   ICMP Redirects are used to send routing information to other hosts. As a
#   host itself does not act as a router (in a host only configuration), there
#   is no need to send redirects.
- name: Disabe sending of IPv4 redirects (send_redirects)
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: '0'
    sysctl_set: true

- name: Disabe sending of IPv4 redirects (send_redirects)
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.send_redirects
    value: '0'
    sysctl_set: true


# CIS Controls Linux Benchmark
# Benchmark: Ensure suspicious packets are logged
# Description:
#   When enabled, this feature logs packets with un-routable source addresses to
#   the kernel log.
- name: Enable logging of Martian packets (all.log_martians)
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.log_martians
    value: '1'
    sysctl_set: true

- name: Enable logging of Martian packets (default.log_martians)
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.log_martians
    value: '1'
    sysctl_set: true

# CIS Controls Linux Benchmark
# Benchmark: Ensure broadcast ICMP requests are ignored
# Description:
#   Setting net.ipv4.icmp_echo_ignore_broadcasts to 1 will cause the system to
#   ignore all ICMP echo and timestamp requests to broadcast and multicast
#   addresses.
- name: Ignore ICMP echo broadcasts (icmp_echo_ignore_broadcasts)
  ansible.posix.sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: '1'
    sysctl_set: true
