---
- name: Install vim-enhanced on RedHat
  ansible.builtin.package:
    name: vim-enhanced
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install vim on Ubuntu
  ansible.builtin.package:
    name: vim
    state: present
  when: ansible_facts['os_family'] == "Ubuntu"
